# Branches with names starting with `example` are meant to be long living branches used as
# documentation/usage example.
# After accepting the branch, the main PR should be closed
on:
  pull_request

jobs:
  example-branches-checks:
    name: Example branch management
    if: ${{ startsWith(github.head_ref, 'example') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        name: Set example label
        with:
          labels: |
            example
      - name: Example branches are not meant to be merged
        run: |
          echo "Example branches are not meant to be merged"
          exit 1