name: Prepare prod release
on:
  workflow_dispatch:
  schedule:
      - cron: "0 0 * * 1" # Every Monday midnight
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: canary
          title: "Release prod"
          team-reviewers: "@saleor/devtools"
